/* global window */
(function () {
  var players = [
    {
      name: "Željko Bilić",
      nickname: "Žele",
      image: "./assets/player-promos/ppip_bilic_zeljko_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Smeš iz bilo koje pozicije",
      weakness: "Treba štedit energiju za smeš",
      quote: "Športski pozdrav!",
      accent: "#f5b700",
    },
    {
      name: "Marko Dragunić",
      nickname: "Dragi",
      image: "./assets/player-promos/ppip_dragunic_marko_avatar_v1.png",
      imageScale: "0.92",
      weapon: "Veliki taktičar sa jako neugodnijom servom.",
      weakness: "Teško odvaja noge od poda",
      quote: "Sad si dobio živnotnu lekciju!",
      accent: "#ff6b35",
    },
    {
      name: "Mateo Gugić",
      nickname: "Greg",
      image: "./assets/player-promos/ppip_gugic_mateo_avatar_v1.png",
      imageScale: "0.92",
      weapon: "Bijes",
      weakness: "Bijes",
      quote: "AAAAAAAAAAAAAAAAAAAAAAAAA",
      accent: "#7bdff2",
    },
    {
      name: "Filip Iviš",
      nickname: "Profesor",
      image: "./assets/player-promos/ppip_ivis_filip_avatar_v1.png",
      imageScale: "0.93",
      weapon: "Školovao je mnoge samoprozvane doktore i profesionalce",
      weakness: "Dvije neforsirane greške dijele ga od raspada",
      quote: "Je li ovo moguće?!",
      accent: "#9ef01a",
    },
    {
      name: "Antonio Jonjić",
      nickname: "Zagadur",
      image: "./assets/player-promos/ppip_jonjic_antonio_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Udarac koji nisu ni državni padel prvaci uspjeli pročitat, jednom riječju 'SPECIJALKA'.",
      weakness: "Partner Tomke.",
      quote: "Umoria sam se od razmišljanja...",
      accent: "#ff4d8d",
    },
    {
      name: "Borna Katavić",
      nickname: "Taksist",
      image: "./assets/player-promos/ppip_katavic_borna_avatar_v1.png",
      imageScale: "0.92",
      weapon: "Noćna tarifa",
      weakness: "Ubojit poput pištolja na vodu",
      quote: "Još jednu malu?",
      accent: "#00c2a8",
    },
    {
      name: "Vanja Lopušinsky",
      nickname: "Vanja",
      image: "./assets/player-promos/ppip_lopusinsky_vanja_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Snaga živaca",
      weakness: "Snaga živaca",
      quote: "Bez živaca bi bia kurac od igrača.",
      accent: "#ffd166",
    },
    {
      name: "Ivan Martinac",
      nickname: "Šef",
      image: "./assets/player-promos/ppip_martinac_ivan_avatar_v1.png",
      imageScale: "0.93",
      weapon: "Forhend paralela",
      weakness: "Bivši fitnes trener još uvijek čeka na povratak forme od prije 10 godina",
      quote: "Rješit cemo nešto...",
      accent: "#8ecae6",
    },
    {
      name: "Marko Martinović",
      nickname: "Markan",
      image: "./assets/player-promos/ppip_martinovic_marko_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Dragi",
      weakness: "Uvik na rubu",
      quote: "A dragi",
      accent: "#f77f00",
    },
    {
      name: "Borna Mešin",
      nickname: "Mešo",
      image: "./assets/player-promos/ppip_mesin_borna_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Nije opasan",
      weakness: "Bez ruke i kolina, mnogima nije jasno ni kako stoji na nogama",
      quote: "Sinoc sam opet bia u programu..",
      accent: "#b5179e",
    },
    {
      name: "Franko Miočić",
      nickname: "Stariji brat",
      image: "./assets/player-promos/ppip_miocic_franko_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Beckend volejom ubija, a forhenda se i sam boji",
      weakness: "Lob nebi diga ni da o životu ovisi...",
      quote: "Lob je za pičiće",
      accent: "#06d6a0",
    },
    {
      name: "Ian Miočić",
      nickname: "Ean",
      image: "./assets/player-promos/ppip_miocic_ian_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Samo jako",
      weakness: "Samo jako",
      quote: "Sirova snaga!",
      accent: "#4cc9f0",
    },
    {
      name: "Antonio Rajković",
      nickname: "Ćaća",
      image: "./assets/player-promos/ppip_rajkovic_antonio_avatar_v1.png",
      imageScale: "0.94",
      weapon: "99,99",
      weakness: "99,99",
      quote: "99,99",
      accent: "#f72585",
    },
    {
      name: "Jurica Šeparović",
      nickname: "Šep",
      image: "./assets/player-promos/ppip_separovic_jurica_avatar_v1.png",
      imageScale: "0.94",
      weapon: "Precizan kao snajper",
      weakness: "Spor ko blato",
      quote: "Sve ti jebem!",
      accent: "#90be6d",
    },
    {
      name: "Mario Sočo",
      nickname: "Kapetan",
      image: "./assets/player-promos/ppip_soco_mario_avatar_v2.png",
      imageScale: "0.9",
      weapon: "Čekat priliku i izmorit protivnika",
      weakness: "Često čekanje prilike traje predugo",
      quote: "Ja ja ja ja ja!",
      accent: "#f9844a",
    },
    {
      name: "Ivan Tomić",
      nickname: "Starac",
      image: "./assets/player-promos/ppip_tomic_ivan_avatar_v1.png",
      imageScale: "0.92",
      weapon: "Priča se da je pobjedio zid na 1v1 sa čak dvije izmjene više",
      weakness: "Rado bi diga lob i na voleju, ali ne ide",
      quote: "Ala čekaju me doma lazanje u šaheru...",
      accent: "#577590",
    }
  ];

  window.PPIP_PLAYERS = players;
})();
