/* global window */
(function () {
  var players = [
    {
      name: "Željko Bilić",
      nickname: "Žele",
      image: "./assets/player-promos/ppip_bilic_zeljko_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Ritam",
      weakness: "Previše kontrole",
      quote: "Raspa sam se. Športski pozdrav!",
      accent: "#f5b700",
    },
    {
      name: "Marko Dragunić",
      nickname: "Dragi",
      image: "./assets/player-promos/ppip_dragunic_marko_avatar_v2.png",
      imageScale: "0.92",
      weapon: "Serva",
      weakness: "Brzina",
      quote: "Ovo ti je životna lekcija...",
      accent: "#ff6b35",
    },
    {
      name: "Mateo Gugić",
      nickname: "Greg",
      image: "./assets/player-promos/ppip_gugic_mateo_avatar_v1.png",
      imageScale: "0.92",
      weapon: "Bijes",
      weakness: "Bijes",
      quote: "AAAAAAAAAAAAAAAAAAAAAAAAA",
      accent: "#7bdff2",
    },
    {
      name: "Filip Iviš",
      nickname: "Profesor",
      image: "./assets/player-promos/ppip_ivis_filip_avatar_v1.png",
      imageScale: "0.93",
      weapon: "Završnica",
      weakness: "Strpljenje",
      quote: "Jel ovo moguće?",
      accent: "#9ef01a",
    },
    {
      name: "Antonio Jonjić",
      nickname: "Zagadur",
      image: "./assets/player-promos/ppip_jonjic_antonio_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Promjena ritma",
      weakness: "Plan B",
      quote: "Umoria sam se od razmišljanja...",
      accent: "#ff4d8d",
    },
    {
      name: "Borna Katavić",
      nickname: "Taksist",
      image: "./assets/player-promos/ppip_katavic_borna_avatar_v1.png",
      imageScale: "0.92",
      weapon: "Obrana",
      weakness: "Napad iz prve",
      quote: "Još jednu malu?",
      accent: "#00c2a8",
    },
    {
      name: "Vanja Lopušinsky",
      nickname: "Vanja",
      image: "./assets/player-promos/ppip_lopusinsky_vanja_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Presretanje",
      weakness: "Direktan duel",
      quote: "Bez živaca bi bia kurac od igrača.",
      accent: "#ffd166",
    },
    {
      name: "Ivan Martinac",
      nickname: "Šef",
      image: "./assets/player-promos/ppip_martinac_ivan_avatar_v1.png",
      imageScale: "0.93",
      weapon: "Forhend paralela",
      weakness: "Stamina",
      quote: "Rješit cemo nešto...",
      accent: "#8ecae6",
    },
    {
      name: "Marko Martinović",
      nickname: "Markan",
      image: "",
      weapon: "Kretanje",
      weakness: "Stajanje u mjestu",
      quote: "A dragi",
      accent: "#f77f00",
    },
    {
      name: "Borna Mesin",
      nickname: "Mešo",
      image: "./assets/player-promos/ppip_mesin_borna_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Smash",
      weakness: "Kratka lopta",
      quote: "Sinoc sam opet bia u programu.",
      accent: "#b5179e",
    },
    {
      name: "Franko Miočić",
      nickname: "Stariji brat",
      image: "./assets/player-promos/ppip_miocic_franko_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Taktika",
      weakness: "Previše kalkulacije",
      quote: "Lob je za pičiće",
      accent: "#06d6a0",
    },
    {
      name: "Ian Miočić",
      nickname: "Ean",
      image: "./assets/player-promos/ppip_miocic_ian_avatar_v1.png",
      imageScale: "0.9",
      weapon: "Brze ruke",
      weakness: "Strpljenje",
      quote: "Sirova snaga!",
      accent: "#4cc9f0",
    },
    {
      name: "Antonio Rajković",
      nickname: "Ćaća",
      image: "./assets/player-promos/ppip_rajkovic_antonio_avatar_v1.png",
      imageScale: "0.94",
      weapon: "Mreža",
      weakness: "Duboke lopte",
      quote: "Staklo, mriža, raspad...",
      accent: "#f72585",
    },
    {
      name: "Jurica Šeparović",
      nickname: "Šep",
      image: "./assets/player-promos/ppip_separovic_jurica_avatar_v1.png",
      imageScale: "0.94",
      weapon: "Kutovi",
      weakness: "Sirova snaga",
      quote: "Sve ti jebem!",
      accent: "#90be6d",
    },
    {
      name: "Mario Sočo",
      nickname: "Kapetan",
      image: "./assets/player-promos/ppip_soco_mario_avatar_v2.png",
      imageScale: "0.9",
      weapon: "Skok",
      weakness: "Mirni poeni",
      quote: "Ja ja ja ja ja!",
      accent: "#f9844a",
    },
    {
      name: "Ivan Tomić",
      nickname: "Starac",
      image: "./assets/player-promos/ppip_tomic_ivan_avatar_v1.png",
      imageScale: "0.92",
      weapon: "Iskustvo",
      weakness: "Duge razmjene",
      quote: "Triba termine produžit na 5h",
      accent: "#577590",
    }
  ];

  window.PPIP_PLAYERS = players;
})();
