/* global window */
(function () {
  var players = [
    {
      name: "Željko Bilić",
      nickname: "Žele",
      image: "./assets/player-promos/ppip_bilic_zeljko_avatar_v1.png",
      imageScale: "0.9",
      odds: "99,00",
      weapon: "Ubojit iz bilo koje pozicije na terenu",
      weakness: "Čisti fokus na napad, izbjegava obranu k'o poziv za vojsku",
      quote: "Športski pozdrav!",
      accent: "#f5b700",
    },
    {
      name: "Marko Dragunić",
      nickname: "Dragi",
      image: "./assets/player-promos/ppip_dragunic_marko_avatar_v1.png",
      imageScale: "0.92",
      odds: "80,00",
      weapon: "Veliki taktičar s ubojitim servisom",
      weakness: "Teško odvaja noge od poda",
      quote: "Sad si dobio životnu lekciju!",
      accent: "#ff6b35",
    },
    {
      name: "Mateo Gugić",
      nickname: "Greg",
      image: "./assets/player-promos/ppip_gugic_mateo_avatar_v1.png",
      imageScale: "0.92",
      odds: "85,00",
      weapon: "Bijes",
      weakness: "Bijes",
      quote: "AAAAAAAAAAAAAAAAAAAAAAAAA",
      accent: "#7bdff2",
    },
    {
      name: "Filip Iviš",
      nickname: "Profesor",
      image: "./assets/player-promos/ppip_ivis_filip_avatar_v1.png",
      imageScale: "0.93",
      odds: "2,70",
      weapon: "Školovao je mnoge",
      weakness: "Dvije neforsirane pogreške dijele ga od raspada",
      quote: "Je li ovo moguće?!",
      accent: "#9ef01a",
    },
    {
      name: "Antonio Jonjić",
      nickname: "Zagadur",
      image: "./assets/player-promos/ppip_jonjic_antonio_avatar_v1.png",
      imageScale: "0.9",
      odds: "5,00",
      weapon: "Udarac koji nisu ni državni padel prvaci uspjeli pročitat, jednom riječju 'specijalka'.",
      weakness: "Partner Starac",
      quote: "Moj prijatelj Željko...",
      accent: "#ff4d8d",
    },
    {
      name: "Borna Katavić",
      nickname: "Taksist",
      image: "./assets/player-promos/ppip_katavic_borna_avatar_v1.png",
      imageScale: "0.92",
      odds: "99,00",
      weapon: "Noćna tarifa",
      weakness: "Ubojit poput pištolja na vodu",
      quote: "Još jednu malu?",
      accent: "#00c2a8",
    },
    {
      name: "Vanja Lopušinsky",
      nickname: "Vanja",
      image: "./assets/player-promos/ppip_lopusinsky_vanja_avatar_v1.png",
      imageScale: "0.9",
      odds: "15,00",
      weapon: "Snaga živaca",
      weakness: "Snaga živaca",
      quote: "Bez živaca bi bia kurac od igrača.",
      accent: "#ffd166",
    },
    {
      name: "Ivan Martinac",
      nickname: "Šef",
      image: "./assets/player-promos/ppip_martinac_ivan_avatar_v1.png",
      imageScale: "0.93",
      odds: "99,00",
      weapon: "Forhend paralela",
      weakness: "Bivši fitnes trener još uvijek čeka na povratak forme od prije 10 godina...",
      quote: "Rješit ćemo nešto...",
      accent: "#8ecae6",
    },
    {
      name: "Marko Martinović",
      nickname: "Markan",
      image: "./assets/player-promos/ppip_martinovic_marko_avatar_v1.png",
      imageScale: "0.9",
      odds: "99,00",
      weapon: "Dragi",
      weakness: "Uvik na rubu živaca i zakona",
      quote: "A dragi",
      accent: "#f77f00",
    },
    {
      name: "Borna Mešin",
      nickname: "Mešo",
      image: "./assets/player-promos/ppip_mesin_borna_avatar_v1.png",
      imageScale: "0.9",
      odds: "∞",
      weapon: "Opasan kao kamilica",
      weakness: "Još jedna ozljeda dijeli ga od para PPiP-a.",
      quote: "Sinoć sam opet bia u programu...",
      accent: "#b5179e",
    },
    {
      name: "Franko Miočić",
      nickname: "Stariji brat",
      image: "./assets/player-promos/ppip_miocic_franko_avatar_v1.png",
      imageScale: "0.9",
      odds: "2,50",
      weapon: "Bekend volejom ubija, a forhenda se i sam boji",
      weakness: "Teniski dani ostavili su traga na stabilnosti živaca",
      quote: "Lob ne bi diga ni da mi o životu ovisi",
      accent: "#06d6a0",
    },
    {
      name: "Ian Miočić",
      nickname: "Ean",
      image: "./assets/player-promos/ppip_miocic_ian_avatar_v1.png",
      imageScale: "0.9",
      odds: "25,00",
      weapon: "Svaki udarac je ubojit",
      weakness: "Ima samo jednu brzinu",
      quote: "Bili smo ja i Iviš...",
      accent: "#4cc9f0",
    },
    {
      name: "Antonio Rajković",
      nickname: "Ćaća",
      image: "./assets/player-promos/ppip_rajkovic_antonio_avatar_v1.png",
      imageScale: "0.94",
      odds: "99,00",
      weapon: "Zna nekad skratit ako se sve poklopi",
      weakness: "Strpljiv kao petarda s upaljenim fitiljem",
      quote: "99,99",
      accent: "#f72585",
    },
    {
      name: "Jurica Šeparović",
      nickname: "Šep",
      image: "./assets/player-promos/ppip_separovic_jurica_avatar_v1.png",
      imageScale: "0.94",
      odds: "15,00",
      weapon: "Precizan kao snajper",
      weakness: "Spor kao blato",
      quote: "Sve ti jebem!",
      accent: "#90be6d",
    },
    {
      name: "Mario Sočo",
      nickname: "Kapetan",
      image: "./assets/player-promos/ppip_soco_mario_avatar_v2.png",
      imageScale: "0.9",
      odds: "2,00",
      weapon: "Strpljiv kao da mu plaćaju po odbijanju loptice od stakla",
      weakness: "Malene mu kvare fokus",
      quote: "Ja ja ja ja ja!",
      accent: "#f9844a",
    },
    {
      name: "Ivan Tomić",
      nickname: "Starac",
      image: "./assets/player-promos/ppip_tomic_ivan_avatar_v1.png",
      imageScale: "0.92",
      odds: "22,00",
      weapon: "Priča se da je pobijedio zid 1v1",
      weakness: "Napadački opasan kao Švicarska vojska",
      quote: "Ala čekaju me doma lazanje u šaheru...",
      accent: "#577590",
    }
  ];

  window.PPIP_PLAYERS = players;
})();
